import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  addJournalEntry,
  editJournalEntry,
  getAllJournalEntries,
  getJournalEntries,
  getTraits,
} from '../src/redux/actions/journal';
import {
  EDIT_JOURNAL_ENTRY,
  GET_ALL_JOURNAL_ENTRIES,
  GET_JOURNAL_ENTRIES,
  GET_TRAITS,
  SET_JOURNAL_ENTRY,
} from '../src/redux/constants';
import journalReducer from '../src/redux/reducer/journal';

describe('journal slice boundary', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('initial state preserves the legacy journal slice shape', () => {
    const state = journalReducer(undefined, { type: '@@INIT' });

    expect(state).toEqual(
      expect.objectContaining({
        allJournalEntriesList: [],
        journalEntries: {},
        allEntries: null,
      }),
    );
    expect(Array.isArray(state.allTraits)).toBe(true);
  });

  test('same-day lookup matches entries across different times on the same calendar day', () => {
    const matchingEntry = {
      id: 'journal-1',
      createdOn: new Date('2026-04-16T08:15:00.000Z').getTime(),
      DailyEntry: { feelingRate: '4' },
    };
    const state = {
      ...journalReducer(undefined, { type: '@@INIT' }),
      allJournalEntriesList: [
        {
          id: 'journal-0',
          createdOn: new Date('2026-04-15T23:00:00.000Z').getTime(),
          DailyEntry: { feelingRate: '2' },
        },
        matchingEntry,
      ],
    };

    const nextState = journalReducer(state, {
      type: GET_JOURNAL_ENTRIES,
      payload: { date: new Date('2026-04-16T21:45:00.000Z').getTime() },
    });

    expect(nextState.allEntries).toBe(matchingEntry);
  });

  test('missing same-day lookup stores null in allEntries', () => {
    const state = {
      ...journalReducer(undefined, { type: '@@INIT' }),
      allJournalEntriesList: [
        {
          id: 'journal-1',
          createdOn: new Date('2026-04-15T08:15:00.000Z').getTime(),
          DailyEntry: { feelingRate: '4' },
        },
      ],
    };

    const nextState = journalReducer(state, {
      type: GET_JOURNAL_ENTRIES,
      payload: { date: new Date('2026-04-16T21:45:00.000Z').getTime() },
    });

    expect(nextState.allEntries).toBeNull();
  });

  test('add-entry appends a new entry with createdOn and autogenerated id', () => {
    const date = new Date('2026-04-16T21:45:00.000Z').getTime();
    const entryData = {
      DailyEntry: { feelingRate: '5' },
      WeightLog: { weight: '180' },
    };
    const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.123456789);

    try {
      const nextState = journalReducer(undefined, {
        type: SET_JOURNAL_ENTRY,
        payload: { date, data: entryData },
      });

      expect(nextState.allJournalEntriesList).toHaveLength(1);
      expect(nextState.allJournalEntriesList[0]).toEqual({
        ...entryData,
        createdOn: date,
        id: '4fzzzxjylrx',
      });
    } finally {
      randomSpy.mockRestore();
    }
  });

  test('edit-entry shallow-merges the matching journal entry', () => {
    const originalEntry = {
      id: 'journal-1',
      createdOn: new Date('2026-04-16T08:15:00.000Z').getTime(),
      DailyEntry: { feelingRate: '4' },
      WeightLog: { weight: '180' },
      notes: 'keep me',
    };
    const state = {
      ...journalReducer(undefined, { type: '@@INIT' }),
      allJournalEntriesList: [originalEntry],
    };

    const nextState = journalReducer(state, {
      type: EDIT_JOURNAL_ENTRY,
      payload: {
        id: 'journal-1',
        data: {
          DailyEntry: { feelingRate: '5' },
          newField: true,
        },
      },
    });

    expect(nextState).not.toBe(state);
    expect(nextState.allJournalEntriesList).not.toBe(state.allJournalEntriesList);
    expect(nextState.allJournalEntriesList[0]).toEqual({
      ...originalEntry,
      DailyEntry: { feelingRate: '5' },
      newField: true,
    });
  });

  test('missing-id edit returns the same state and entries references', () => {
    const originalEntry = {
      id: 'journal-1',
      createdOn: new Date('2026-04-16T08:15:00.000Z').getTime(),
      DailyEntry: { feelingRate: '4' },
    };
    const state = {
      ...journalReducer(undefined, { type: '@@INIT' }),
      allJournalEntriesList: [originalEntry],
    };

    const nextState = journalReducer(state, {
      type: EDIT_JOURNAL_ENTRY,
      payload: {
        id: 'missing-id',
        data: { DailyEntry: { feelingRate: '1' } },
      },
    });

    expect(nextState).toBe(state);
    expect(nextState.allJournalEntriesList).toBe(state.allJournalEntriesList);
  });

  test('getTraits dispatches parsed stored traits and returns true', async () => {
    const storedTraits = [{ id: 'trait-1', name: 'Calm' }];
    const dispatch = jest.fn();

    AsyncStorage.getItem.mockResolvedValueOnce(JSON.stringify(storedTraits));

    await expect(getTraits()(dispatch)).resolves.toBe(true);
    expect(AsyncStorage.getItem).toHaveBeenCalledWith('traits');
    expect(dispatch).toHaveBeenCalledWith({
      type: GET_TRAITS,
      payload: storedTraits,
    });
  });

  test('getTraits falls back to an empty array when storage is empty', async () => {
    const dispatch = jest.fn();

    AsyncStorage.getItem.mockResolvedValueOnce(null);

    await expect(getTraits()(dispatch)).resolves.toBe(true);
    expect(AsyncStorage.getItem).toHaveBeenCalledWith('traits');
    expect(dispatch).toHaveBeenCalledWith({
      type: GET_TRAITS,
      payload: [],
    });
  });

  test('getAllJournalEntries dispatches its current action and resolves true', async () => {
    const dispatch = jest.fn();

    await expect(getAllJournalEntries()(dispatch)).resolves.toBe(true);
    expect(dispatch).toHaveBeenCalledWith({ type: GET_ALL_JOURNAL_ENTRIES });
  });

  test('getJournalEntries dispatches the provided date payload without a return contract', async () => {
    const dispatch = jest.fn();
    const date = new Date('2026-04-16T21:45:00.000Z').getTime();

    await expect(getJournalEntries(date)(dispatch)).resolves.toBeUndefined();
    expect(dispatch).toHaveBeenCalledWith({
      type: GET_JOURNAL_ENTRIES,
      payload: { date },
    });
  });

  test('addJournalEntry dispatches SET_JOURNAL_ENTRY and returns true', async () => {
    const dispatch = jest.fn();
    const date = new Date('2026-04-16T21:45:00.000Z').getTime();
    const data = { DailyEntry: { feelingRate: '5' } };

    await expect(addJournalEntry(date, data)(dispatch)).resolves.toBe(true);
    expect(dispatch).toHaveBeenCalledWith({
      type: SET_JOURNAL_ENTRY,
      payload: { date, data },
    });
  });

  test('editJournalEntry dispatches EDIT_JOURNAL_ENTRY and returns true', async () => {
    const dispatch = jest.fn();
    const data = { DailyEntry: { feelingRate: '5' } };

    await expect(editJournalEntry('journal-1', data)(dispatch)).resolves.toBe(true);
    expect(dispatch).toHaveBeenCalledWith({
      type: EDIT_JOURNAL_ENTRY,
      payload: { id: 'journal-1', data },
    });
  });
});
